<a href="https://colab.research.google.com/github/riskakurniaa/Machine-Learning/blob/Jobsheet1/Jobsheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def norm_data(data):
    """
    Melakukan normalisasi data.

    Parameters:
        data (list): Data yang akan dinormalisasi

    Returns:
        data (list): Data hasil normalisasi
    """
    data_max = max(data)
    data_min = min(data)
    data_len = len(data)

    for i in range(0, data_len):
        data[i] = (data[i] - data_min) / (data_max - data_min)

    return data

# Contoh Penggunaan
data = [10, 11, 12, 14, 16]
n_data = norm_data(data)  # melakukan normalisasi
print(n_data)

[0.0, 0.16666666666666666, 0.3333333333333333, 0.6666666666666666, 1.0]


In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Set opsi tampilan numpy
np.set_printoptions(precision=6)  # Bulatkan 4 angka koma
np.set_printoptions(suppress=True)  # Hilangkan nilai (e)

# Kita akan membentuk data
# Hal ini dikarenakan, scikit-learn hanya menerima input
# dalam bentuk n-dimensional array
data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

# Ubah data ke bentuk numpy n-dimensional array
data = np.asarray(data)

# Cetak data asli
print('Data Asli:')
print(data)

# Mendefinisikan objek MinMaxScaler
scaler = MinMaxScaler()

# Transformasikan data
scaled = scaler.fit_transform(data)

# Cetak data hasil normalisasi
print('Data Normalisasi:')
print(scaled)


Data Asli:
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Normalisasi:
[[1.       0.      ]
 [0.285714 1.      ]
 [0.       0.058116]]


In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Set opsi tampilan numpy
np.set_printoptions(precision=4)  # Bulatkan 4 angka di belakang koma
np.set_printoptions(suppress=True)  # Hilangkan notasi eksponensial (e)

# Kita akan membentuk data
# Hal ini dikarenakan, scikit-learn hanya menerima input
# dalam bentuk n-dimensional array
data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

# Ubah data ke bentuk numpy n-dimensional array
data = np.asarray(data)

# Cetak data asli
print('Data Asli:')
print(data)

# Mendefinisikan objek StandardScaler
scaler = StandardScaler()

# Transformasikan data
scaled = scaler.fit_transform(data)

# Cetak data hasil standarisasi
print('Data Standarisasi:')
print(scaled)

Data Asli:
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Standarisasi:
[[ 1.3587 -0.7696]
 [-0.3397  1.4123]
 [-1.019  -0.6428]]


In [ ]:
from sklearn.preprocessing import OrdinalEncoder

# Inisiasi obyek Ordinal Encoder
oe = OrdinalEncoder()

# Definisikan data dalam bentuk 2D
data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarata'],
    ['Politeknik Negeri Semarang']
]

# Transformasi menggunakan Ordinal Encoder
transform_oe = oe.fit_transform(data)

# Cetak data asli dan hasil transformasi
print('Data Asli:')
print(data)
print('Data Transformasi Ordinal Encoder:')
print(transform_oe)

Data Asli:
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarata'], ['Politeknik Negeri Semarang']]
Data Transformasi Ordinal Encoder:
[[2.]
 [0.]
 [1.]
 [3.]]


In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Inisiasi obyek Ordinal Encoder
ohe = OneHotEncoder()

# Definisikan data dalam bentuk 2D
data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarata'],
    ['Politeknik Negeri Semarang']
]

# Transformasi menggunakan Ordinal Encoder
transform_ohe = ohe.fit_transform(data)

# Cetak data asli dan hasil transformasi
print('Data Asli:')
print(data)
print('Data Transformasi Ordinal Encoder:')
print(transform_ohe.toarray())

Data Asli:
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarata'], ['Politeknik Negeri Semarang']]
Data Transformasi Ordinal Encoder:
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Inisiasi obyek Ordinal Encoder
ohe = OneHotEncoder(drop='first')

# Definisikan data dalam bentuk 2D array
data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarata'],
    ['Politeknik Negeri Semarang']
]

# Transformasi Ordinal Encoder
transform_ohe = ohe.fit_transform(data)

# Cetak data asli dan hasil transformasi
print('Data Asli:')
print(data)
print('Data Transformasi One-Hot Encoding:')
print(transform_ohe.toarray())

Data Asli:
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarata'], ['Politeknik Negeri Semarang']]
Data Transformasi One-Hot Encoding:
[[0. 1. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [ ]:
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the mouse',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

In [ ]:
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

from sklearn.feature_extraction.text import TfidfVectorizer

#Inisiasi obyek TFidfVectorixer
vect = TfidfVectorizer(stop_words='english')

#Pembobotan TF-IDF
resp = vect.fit_transform(corpus)

#cetak hasil
print('Hasil TF-IDF')
print(resp)

print('Hasil Token')
vect.get_feature_names_out()

Hasil TF-IDF
  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811
Hasil Token


array(['ate', 'away', 'cat', 'end', 'finally', 'house', 'little', 'mouse',
       'ran', 'saw', 'story', 'tiny'], dtype=object)

In [ ]:
vect.get_feature_names_out()

array(['ate', 'away', 'cat', 'corpus', 'end', 'finally', 'house',
       'little', 'mouse', 'ran', 'saw', 'story', 'tiny'], dtype=object)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Membaca file 'corpus.txt'
with open('corpus.txt') as file:
    corpus = file.readlines()

# Inisiasi obyek TfidfVectorizer, mengabaikan stopwords seperti 'the'
vect = TfidfVectorizer(stop_words='english')

# Proses pembobotan TF-IDF
resp = vect.fit_transform(corpus)

# Cetak hasil TF-IDF dalam bentuk matriks
print('Hasil TF-IDF:')
print(resp)

# Cetak token yang digunakan (fitur yang dipakai)
print('Hasil Token:')
print(vect.get_feature_names_out())

Hasil TF-IDF:
  (0, 3)	1.0
  (1, 8)	0.297446234188861
  (1, 7)	0.5512185706132869
  (1, 12)	0.5512185706132869
  (1, 6)	0.5512185706132869
  (2, 10)	0.7106281860049563
  (2, 2)	0.5898824226331707
  (2, 8)	0.3834661767662525
  (3, 1)	0.5621224523484127
  (3, 9)	0.5621224523484127
  (3, 8)	0.6066602814851265
  (4, 0)	0.579262311604141
  (4, 5)	0.579262311604141
  (4, 2)	0.48083746527154797
  (4, 8)	0.31257907911644855
  (5, 11)	0.6606476647333884
  (5, 4)	0.6606476647333884
  (5, 8)	0.3564958992255601
Hasil Token:
['ate' 'away' 'cat' 'corpus' 'end' 'finally' 'house' 'little' 'mouse'
 'ran' 'saw' 'story' 'tiny']


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Buka dan baca file corpus.txt
with open('corpus.txt', 'r') as file:
    corpus = file.readlines()

# Hapus karakter newline pada setiap kalimat
corpus = [line.strip() for line in corpus]

# Inisiasi obyek TFidfVectorizer
vect = TfidfVectorizer(stop_words='english')

# Pembobotan TF-IDF
resp = vect.fit_transform(corpus)

# Cetak hasil TF-IDF (Matriks Sparse)
print('Hasil TF-IDF (Sparse Matrix):')
print(resp)

# Cetak token setelah penghapusan stopword
print('Hasil Token (Fitur yang Digunakan):')
print(vect.get_feature_names_out())

Hasil TF-IDF (Sparse Matrix):
  (0, 3)	1.0
  (1, 8)	0.297446234188861
  (1, 7)	0.5512185706132869
  (1, 12)	0.5512185706132869
  (1, 6)	0.5512185706132869
  (2, 10)	0.7106281860049563
  (2, 2)	0.5898824226331707
  (2, 8)	0.3834661767662525
  (3, 1)	0.5621224523484127
  (3, 9)	0.5621224523484127
  (3, 8)	0.6066602814851265
  (4, 0)	0.579262311604141
  (4, 5)	0.579262311604141
  (4, 2)	0.48083746527154797
  (4, 8)	0.31257907911644855
  (5, 11)	0.6606476647333884
  (5, 4)	0.6606476647333884
  (5, 8)	0.3564958992255601
Hasil Token (Fitur yang Digunakan):
['ate' 'away' 'cat' 'corpus' 'end' 'finally' 'house' 'little' 'mouse'
 'ran' 'saw' 'story' 'tiny']
